project:
  type: website
  output-dir: docs

website:
  title: "The 2024 ISV Euro competition"
  navbar:
    right:
      - about.qmd
      - rules.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css



