---
title: "Spain - Italy 1-0"
author: "Håvard Strand"
date: "last-modified"
categories: [update]
execute:
  echo: false
---

# Tuesday 19th June 2024, Spain - Italy 1-0

Spain is through, and so is probably Italy. 


```{r init, echo=FALSE, message=FALSE , warning=FALSE}

library(tidyverse)
library(igraph)
library(readxl)
library(knitr)

knitr::opts_chunk$set(out.width = "100%")

```

Vegard is now firmly in the lead. As the draw strike came to an end, so did Jon's climb. Halvard is back in second. Miro and Linda edged their way into top five.

Previous kosmonaut Øyvind is now in 14th place. Things change.



```{r graph, echo = FALSE, warning=FALSE,  fig.height=10, fig.width=10}
#| warning: false

invisible(capture.output(Sys.setlocale()))
nettverk <- readr::read_delim("res18.csv", delim=";", col_names = FALSE, locale = locale(encoding = "UTF-8"))
leaderboard <- tibble::as_tibble(nettverk)

leaderboard <- leaderboard %>% arrange_at(ncol(.), desc)

hbar<-leaderboard 
hbar$diff <- hbar$X19-hbar$X18

ggplot(hbar, aes(x=reorder(X1, X19), y=X19, fill = diff )) + 
    geom_bar(stat = 'identity') + 
    scale_y_continuous(limits = c(-5, 380)) +
    coord_flip() + 
    scale_fill_gradient2(low = "red", high="blue") +
    geom_text(aes(label = X19), hjust=-0.75, size = 5 ) + 
    ylab("Points") +
    xlab(" ") +
    theme(axis.text=element_text(size=18), axis.title=element_text(size=18,face="bold"))
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
