---
title: "10 Own goals"
author: "Håvard Strand"
date: "last-modified"
categories: [Qualitative]
execute:
  echo: false
---

# Points to be distributed

Gakpo is not sole top scorer anymore, as his goal was deemed an own goal. That means the tally is 10, which is more than nine, and we have points to distribute.

```{r init, echo=FALSE, message=FALSE , warning=FALSE}

library(tidyverse)
library(readxl)
library(knitr)

knitr::opts_chunk$set(out.width = "100%")

```


```{r knock_46, echo = FALSE, warning=FALSE,  fig.height=10, fig.width=10}

invisible(Sys.setlocale())
poeng_prev <- tbl_df(read.csv("details48_.csv", sep=";", header = FALSE, encoding = "utf-8"))
poeng_prev$total_prev <- poeng_prev$V2 + poeng_prev$V3 + poeng_prev$V4
poeng_prev <- poeng_prev %>% select(V1, total_prev)

poeng <- tbl_df(read.csv("details48.csv", sep=";", header = FALSE))

poeng$total <- poeng$V2 + poeng$V3 + poeng$V4

poeng <- inner_join(poeng, poeng_prev, by="V1")
poeng$diff <- poeng$total - poeng$total_prev

poeng <- rename(poeng, V35 = V4)
poeng <- rename(poeng, V34 = V3)
poeng <- rename(poeng, V36 = V2)
poeng$V34 <-poeng$V34 - poeng$diff


long_pong <- poeng %>% select(V1, V34, V35, V36, total, diff)  %>% gather(key = V, -V1, -total, value = poeng) %>% arrange(V)

invisible(Sys.setlocale())
ggplot(data = long_pong, aes(x = reorder(V1, total), y=poeng, fill = V)) + 
  geom_bar(stat = "identity") +
  coord_flip() +
  geom_text(aes(V1, 0, label = total), hjust = -0.50, size = 5) +
  ylab("Points") +
  xlab(" ") +
  scale_fill_manual(values=c("#AAAAAA", "#990000", "#E69F00", "#56B4E9"), 
                    name="Origin",
                    breaks=c("V36", "V35", "V34", "diff"),
                    labels=c("Group Stage", "Qualitative", "Knockout Stage", "Since Last")) +
  theme(axis.text=element_text(size=18), axis.title=element_text(size=18,face="bold")) +
  theme(legend.title=element_text(size=18), 
    legend.text=element_text(size=18))

```

Jostein, Jacob and Sverke predicted correctly, while the rest of us were wrong. Jostein is now in third, 67 points behind Øyvind, but only 11 points behind Dagfinn.
